Feature/reveal sections scrolling
Web-Dev-Path/web-dev-path pull request #101
Opened 2022-05-13 04:35 UTC by cherylli

|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**issueNumber**](https://github.com/MarianaSouza/web-dev-path/issues/issueNumber) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
yes

#### What is this change?
 all the sections but the Hero.js being revealed only on scrolling and with a translateY effect that simulates a smooth movement towards the top

#### Were there any complications while making this change?
no

#### How did you verify this change?
run locally on firefox, chrome, brave and in responsive design mode

#### When should this be merged?
after reviews

2022-05-13 04:41 UTC, cherylli commented
I have added interestion observer (with a custom hook) on TwoColumns and CardColumns. Which means everything with TwoColumns and CardColumns will have this revealing effect, which works fine for now. I'm not sure if this will affect future contents if these components are to be used elsewhere. 

Another way I can think of is create another component with intersect to wrap around individual front page components

2022-05-20 04:39 UTC, mariana-caldas requested changes
I just have that single request on the footer, @cherylli !
This looks great, thanks!

2022-05-20 04:39 UTC, mariana-caldas commented on components/Footer.js
> +import RevealContentContainer from './RevealContentContainer';
Could you please remove the effect from the footer? Thanks!

2022-05-20 05:23 UTC, cherylli commented on components/Footer.js
> +import RevealContentContainer from './RevealContentContainer';
removed

2022-05-20 21:33 UTC, mariana-caldas approved these changes
LG(reat)TM, @cherylli ! 🥳 
Can we just wait a few days to see if someone else has more feedback before you merge it, pls? Thanks!

2022-05-26 03:50 UTC, merged