Feature/about us first section
Web-Dev-Path/web-dev-path pull request #107
Opened 2022-06-08 01:50 UTC by cherylli

|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**106**](https://github.com/Web-Dev-Path/web-dev-path/issues/106) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
yes

#### What is this change?
1. Add about content and styling (for first section)
2. Restructure components folder 

#### Were there any complications while making this change?
no

#### How did you verify this change?
Run locally in mobile and desktop mode in different screen sizes

#### When should this be merged?
After review

2022-06-08 01:52 UTC, cherylli commented
mostly done waiting for new image.

[![](https://i.imgur.com/vnycDyDm.jpg)](https://i.imgur.com/vnycDyD.png)
new component structure, open to suggestions

2022-06-08 01:57 UTC, cherylli commented on CHANGELOG.md
> +## Unreleased
Added a new ## Unreleased section because of #105 - to avoid conflict when merging

2022-06-15 14:32 UTC, cherylli commented
Not sure if there's already a mobile design. Can't find it on figma, so just using the default TwoColumn mobile view.

2022-06-15 16:06 UTC, mariana-caldas submitted a review, later dismissed
This new file structure makes so much sense, @cherylli ! Thanks so much, you rock! 🚀 
I just see some minor adjustments. Feel free to reach out if you have questions about them.
Could you please request my review again whenever it is ready?

2022-06-15 16:06 UTC, mariana-caldas commented on styles/Title.module.scss
> +.title {
On mobile, I noticed the title is pretty close to the top, @cherylli . Do you think we could adjust that?

![Uploading about-us-title.png…]()

2022-06-15 23:32 UTC, cherylli commented on .gitignore
> +.idea
because I use webstorm locally and it adds an .idea folder. But I can go back to vscode if not acceptable.

2022-06-15 23:40 UTC, cherylli commented on styles/globals.scss
> +.about-us {
you're right we don't need that. But I do need to remove .about-us from the previous block. otherwise it looks like this 
[![](https://i.imgur.com/3sdCiFUm.jpg)](https://i.imgur.com/3sdCiFU.png)

2022-06-16 00:58 UTC, mariana-caldas commented on .gitignore
> +.idea
Ok, that's fine! Thanks for clarifying it.

2022-06-16 00:59 UTC, mariana-caldas commented on styles/globals.scss
> +.about-us {
I see... Well,  the less code the better! :D

2022-06-16 01:06 UTC, cherylli commented on styles/Title.module.scss
> +.title {
The default looks ok. Maybe I don't need Title.module.css. Should I leave it there for possible future use or just remove it completely?

2022-06-16 18:00 UTC, mariana-caldas commented on styles/Title.module.scss
> +.title {
Good point, @cherylli ! Yes, it makes total sense to remove it for now if we're not adding any style to it. Thanks! 🙌🏼

2022-06-18 09:22 UTC, Faith-Nchifor reviewed
The First section looks great! Everything seems to be on point. However, concerning the mobile view, I want to suggest that under the 'About Web Dev Path' heading the images should come before the paragraph rather than after. Great job

2022-06-18 09:30 UTC, cherylli commented
> The First section looks great! Everything seems to be on point. However, concerning the mobile view, I want to suggest that under the 'About Web Dev Path' heading the images should come before the paragraph rather than after. Great job

Thanks. As mentioned before there's no official mobile design yet. so this might be a suggestion to the @Web-Dev-Path/designers team.

2022-06-19 01:22 UTC, camille-granier approved these changes
Looks good to me!

2022-06-19 23:31 UTC, mariana-caldas requested changes
The path organization is amazing, @cherylli ! Such a great job! Could you pls just make the Github and Bitbucket links and connect them to their respective pages?

https://github.com/
https://bitbucket.org/product/

2022-06-20 04:26 UTC, mariana-caldas approved these changes
Yay! "Habemus" first section, @cherylli ! Great job! 🥇 
Can you just wait until Wednesday to merge it so we give some time for more reviews?

2022-06-20 08:35 UTC, cherylli commented
Should we set up a project specific file like prettier or eslint for formatting consistency? I normally use single quotes for most things in js so my auto formatter might have done that.

2022-06-22 00:41 UTC, merged