Made the site a PWA
Web-Dev-Path/web-dev-path pull request #114
Opened 2022-07-11 08:16 UTC by klezi10

|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [113](https://github.com/MarianaSouza/web-dev-path/issues/113) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
Yes.

#### What is this change?
Made the site a Progressive Web App (PWA)

![image](https://user-images.githubusercontent.com/74952593/178216535-3d7e31a9-6cce-4594-aa96-1c597633dc3f.png)

#### Were there any complications while making this change?
Yes, I have been unable to test it with the correct link which is why the PR is still a work in progress. I am currently working on this.

#### How did you verify this change?
Locally. It passed the Lighthouse Progressive Web App test with the localhost link. 

#### When should this be merged?
Once it has been tested in production and after review.

2022-07-11 12:13 UTC, cherylli reviewed
![image](https://user-images.githubusercontent.com/6191116/178261494-6fba4362-a1e2-43f3-95c6-ba257fc627df.png)

2022-07-11 12:13 UTC, cherylli commented on public/favicon/site.webmanifest
> +    "start_url": "https://webdevpath.co/",
`"start_url": "/",`
Changing to this works even in development mode.

2022-07-12 11:53 UTC, cherylli approved these changes

2022-07-13 21:28 UTC, mariana-caldas requested changes
This looks great! We're almost there, @klezi10 and @cherylli !

As explained in the end of [this video](https://www.youtube.com/watch?v=ARNN_zmrwcw&t=714s), we shouldn't commit the auto-generated files sw.js** and worboxes into production.

Could you please remove those 4 files, add the following code to `.gitignore` , generate them locally again by running `yarn install`, test everything locally again and commit the changes to the branch making sure those files are properly ignored? Thanks!
```
# PWA files
**/public/sw.js
**/public/sw.js.map
**/public/worker-*.js
**/public/workbox-*.js
**/public/worker-*.js
**/public/workbox-*.js.map
**/public/worker-*.js.map

2022-07-15 06:29 UTC, mariana-caldas approved these changes
This looks great, @klezi10 !
Could you please wait until Monday to merge it so we give others a chance to review it too?
Thanks so much!

2022-07-19 06:40 UTC, merged

2022-07-20 04:17 UTC, vmcodes commented
Looks great to me. Double checked the Lighthouse reports and saw no issues. 

An off topic suggestion I noticed was that we we're missing a canonical link and robots.txt file which would help with Google indexing :smile: