Chore/footer revamp social media
Web-Dev-Path/web-dev-path pull request #120
Opened 2022-07-25 10:38 UTC by klezi10

|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [116](https://github.com/MarianaSouza/web-dev-path/issues/116) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
Yes.

#### What is this change?
Updated footer styling with social media icons.
I also removed the "changed" part in changelog and added those items under "fixed" in unreleased.

#### Were there any complications while making this change?
No.

#### How did you verify this change?
Locally.

#### When should this be merged?
After review.

2022-07-25 13:08 UTC, cherylli reviewed
Looks good! Just a few small things

2022-07-25 13:08 UTC, cherylli commented on styles/Footer.module.scss
> +    margin: 0 0 revert;
I think this one should be `margin: revert`. My IDE is showing me error

2022-07-25 13:08 UTC, cherylli commented on styles/Footer.module.scss
> +    li:first-child {
not sure if this is the best way to hide the linkedin icon, since it's not very extensible 🤔, Might be better to include a "visible" boolean value in the links?

2022-07-25 13:08 UTC, cherylli commented on styles/Footer.module.scss
> +      max-width: 68px;
2 max-width here

2022-07-25 17:33 UTC, mariana-caldas commented on components/layout/Footer.js
> +              {linksSocial.filter(link => link.isVisible).map(link => (
The use of the `isVisible` property here is perfect! I love it! 🚀

2022-07-25 17:36 UTC, mariana-caldas requested changes
This is looking so great, @klezi10 ! That's amazing!
Love how you use an object property to filter the social media SVGs. Your flexbox implementation is amazing too!

I just have two things to ask, please:

1. Are you OK with solving that small conflict on the Changelog file or do you prefer I do that and record a video for you?
2. Could you please add the same logo hover effect to the social media icons?

Thanks so much!

2022-07-26 06:01 UTC, klezi10 commented
Thank you @mariana-caldas !

>     1. Are you OK with solving that small conflict on the Changelog file or do you prefer I do that and record a video for you?
No worries, I can do it once ready to merge.

>     2. Could you please add the same logo hover effect to the social media icons?
Resolved.

2022-07-27 04:17 UTC, mariana-caldas approved these changes
Great job, @klezi10 !
All yours to merge 🚀

2022-07-27 05:47 UTC, merged