Feature/wanna learn more
Web-Dev-Path/web-dev-path pull request #130
Opened 2022-08-30 12:36 UTC by cherylli

|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**125**](https://github.com/MarianaSouza/web-dev-path/issues/125) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
not yet - todo

#### What is this change?
1. Add wanna learn more part in about page
2. modify TwoColumn to accept a second column of text (or other components) instead of an image

#### Were there any complications while making this change?
no

#### How did you verify this change?
run locally in desktop and mobile view

#### When should this be merged?
after review

2022-09-01 07:31 UTC, klezi10 commented on pages/about.js
> +        />
I'm getting squiggly lines here but no error or any other kinds of messages about it. It seems to work though, and it doesn't work without it. Just wondering.

![image](https://user-images.githubusercontent.com/74952593/187857344-85e2d97c-6592-49af-a1da-3595087aa34a.png)

2022-09-01 07:35 UTC, klezi10 approved these changes
Looks good!

2022-09-01 11:53 UTC, cherylli commented on pages/about.js
> +        />
what error do you see if you mouse over on the error? I don't see any errors here in either vscode or webstorm

2022-09-01 12:30 UTC, klezi10 commented on pages/about.js
> +        />
When I mouse over, I don't see any error messages there either. Maybe it's my settings?

2022-09-01 12:35 UTC, cherylli commented on pages/about.js
> +        />
oh I actually saw it briefly after i rebooted my computer and restarted vscode. It says loading, then after a while the red <TwoColumn is gone. Sorry no idea,

2022-09-01 12:46 UTC, cherylli commented on pages/about.js
> +        />
I see it now. I'm supposed to wrap it in {} ...
![image](https://user-images.githubusercontent.com/6191116/187916652-4dfb490a-1c4a-4bef-9048-6a0ff65c945c.png)

2022-09-02 20:28 UTC, mariana-caldas approved these changes
Great job, @cherylli ! Thanks!
I've adjusted the `ButtonLink` component, so we can open links in an external tab and also changed the style to make sure it looks good on most desktop points, it wasn't great on 1024px before for example.

2022-09-06 03:24 UTC, cherylli commented
Do we need to change the text and link for "How to get started?" since we changed it so they are not sent to slack first?

2022-09-06 20:05 UTC, mariana-caldas commented
> Do we need to change the text and link for "How to get started?" since we changed it so they are not sent to slack first?

Great catch, @cherylli ! 🥇 
I've updated the content in the [mockup](https://www.figma.com/file/Fp0lLB5OWZLJseTs2svGbg/Web-Dev-Path_design?node-id=414%3A936) to:

"After taking a look at our project README and wiki, just send us an email sharing with us about your journey in tech and why you’re interested in joining us.
We've got you!"

I've added the links there to the README and wiki as well. The "Ping Us" link should take the users to the project email, as we see on the "Join us" navigation link. Please let me know if that makes sense, Cheryl! 🚀

2022-09-08 04:38 UTC, cherylli commented
updated. should be good to go

2022-09-08 09:46 UTC, klezi10 commented on pages/about.js
> +          title={<div>Junior Developers</div>}
Is it necessary to have the div wraps here? I think it also works with title='Junior Developers' or 'Experienced Developers'.

2022-09-08 09:56 UTC, klezi10 commented
Just noticed that the "contact us" button under "experienced developers" looks different in the design
https://www.figma.com/file/Fp0lLB5OWZLJseTs2svGbg/Web-Dev-Path_design?node-id=414%3A936

Not sure if it was discussed elsewhere but thought I'd bring it up just in case.

2022-09-08 09:59 UTC, cherylli commented on pages/about.js
> +          title={<div>Junior Developers</div>}
No probably can be removed now. I had it so I can put a line break between the 2 words as in the design but Mariana removed it.

2022-09-08 10:01 UTC, cherylli commented
> Just noticed that the "contact us" button under "experienced developers" looks different in the design
> https://www.figma.com/file/Fp0lLB5OWZLJseTs2svGbg/Web-Dev-Path_design?node-id=414%3A936
> 
> Not sure if it was discussed elsewhere but thought I'd bring it up just in case.

I just assume it's to show the hover style 🤔. Might need a confirmation from the @Web-Dev-Path/designers

2022-09-12 01:07 UTC, mariana-caldas requested changes
This is so great! Thanks so much, @cherylli !
There is only one thing I think we should adjust, please.
Only on mobile, can we remove the "/" and the section padding-bottom? 
![image](https://user-images.githubusercontent.com/20016897/189557784-59351e23-496b-48ae-bf7f-83d18ac27f99.png)

2022-09-12 16:53 UTC, mariana-caldas approved these changes
LG(reat)TM! 🚀 👩🏼‍🎤

2022-09-12 23:41 UTC, merged