Feature/styled components conversion
Web-Dev-Path/web-dev-path pull request #166
Opened 2023-03-30 17:26 UTC by thorrellt

|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**162**](https://github.com/Web-Dev-Path/web-dev-path/issues/162) |

#### Have you updated the CHANGELOG.md file? If not, please do it.

#### What is this change?
Only component converted to Styled Components is ButtonLink
- moved ButtonLink to its own subdirectory
- added _variables.js, _mixins.js, and styles.js (for ButtonLink)  
- removed all sass references from ButtonLink and converted all it's styles to JS

seeking feedback on how the Styled Components were added to ButtonLink before moving forwards and repeating this implementation across the entire project

#### Were there any complications while making this change?
no, some syntax changes were needed to go from sass to js, but no ral complications.

#### How did you verify this change?
in my local browser

#### When should this be merged?
once all the components are converted to styled components.

2023-03-30 18:03 UTC, mariana-caldas commented
Good job on submitting a DRAFT so your decisions become more visual, @thorrellt !

I think your idea of grouping the buttons altogether is on point, however, we're adding `styled-components` to the project now to remove the `customClasses` that make the styling so confusing whenever possible. So, my only suggestion, for now, would be to create more buttons that extend `ButtonLink` functionalities while having their proper CSS, such us `ButtonLinkInvertedGrey` for example. 

Please let me know if that makes sense, Thorrell. If not, don't sweat! I can commit to your branch explaining that better 🙌🏼

2023-03-30 20:23 UTC, thorrellt commented
I understand. Thanks for the feedback. I'll update this component and update the rest with this in mind.

2023-03-31 12:56 UTC, thorrellt commented
I started reworking ButtonLink this morning, and kinda got stuck. It was recommended that I extend ButtonLink to make more buttons ie: ButtonLinkInvertedGrey. My sticking point is that ButtonLinkInvertedGrey is/would never be specifically invoked. The color scheme is passed as a prop from index -> TwoColumn -> ButtonLink. If I start extending styled component in this case, I feel like I would have to:

A. Put some kind of switch or if/else login in TwoColumn to read the props and return each specific button.
B. And by that logic, I should actually even extend TwoColumn and make multiples of it to be called by index.js and wherever it is needed (I haven't looked. Only worked in a small section of code as of yet). 

I still think using props & transient props would be appropriate. This would still remove the dependency on classNames and remove excess classes from our final HTML, although our code would look only slightly different (since attributes and props are written in the exact same way.) I can think of use cases for extending a component but in this case, leveraging props seems the most straightforward, not to mention how much the code base would grow.

However, I am sure I am ignorant to a lot of factors. Am I overlooking something? or, is there a more elegant solution that would allow me to extend components without adding a lot of extra switches and code?

Any thoughts?

2023-04-01 03:09 UTC, mariana-caldas commented
> I started reworking ButtonLink this morning, and kinda got stuck. It was recommended that I extend ButtonLink to make more buttons ie: ButtonLinkInvertedGrey. My sticking point is that ButtonLinkInvertedGrey is/would never be specifically invoked. The color scheme is passed as a prop from index -> TwoColumn -> ButtonLink. If I start extending styled component in this case, I feel like I would have to:
> 
> A. Put some kind of switch or if/else login in TwoColumn to read the props and return each specific button. B. And by that logic, I should actually even extend TwoColumn and make multiples of it to be called by index.js and wherever it is needed (I haven't looked. Only worked in a small section of code as of yet).
> 
> I still think using props & transient props would be appropriate. This would still remove the dependency on classNames and remove excess classes from our final HTML, although our code would look only slightly different (since attributes and props are written in the exact same way.) I can think of use cases for extending a component but in this case, leveraging props seems the most straightforward, not to mention how much the code base would grow.
> 
> However, I am sure I am ignorant to a lot of factors. Am I overlooking something? or, is there a more elegant solution that would allow me to extend components without adding a lot of extra switches and code?
> 
> Any thoughts?

Thanks for communicating so well your process, @thorrellt ! That's the spirit!
I'm taking a look at your branch this weekend to test the possibilities with you in the next few days. Have a great weekend!

2023-04-01 04:02 UTC, mariana-caldas commented
By taking a look at the `TwoColumn` component (attached) I see what you mean, @thorrellt . We can extend the `ButtonLink` to other custom possibilities to get rid of the `props`, however, adding conditionals there would make the code less readable on `TwoColumn` and I agree with you that it does not worth it. We may be able to follow the extended approach without `props` and `customClass` for the others, let's see... 

![image](https://user-images.githubusercontent.com/20016897/229264511-54037b3e-f6ee-4f06-b02f-3c235cbd80de.png)

Good catch on creating a JS file for variables and mixins! 🥇  Before we forget it, I changed a hard-coded color on the `Tag` component.  Please don't hesitate to reach out here or on Slack anytime you feel stuck.

2023-04-05 16:55 UTC, mariana-caldas commented on components/containers/Container/Container.js
> +  className,
Hey, @thorrellt !
Can you check if we still need all those props here? We may be able to keep only "children" here if the other instances allow us to extend the `Container`, for example.

2023-04-05 18:37 UTC, thorrellt commented on components/containers/Container/Container.js
> +  className,
Okay. I was going to check props once I was done with all the styled props. I try to remove dead code when I find it, and I plan to run through everything before I submit my final pull. ...consider it done

2023-04-06 13:47 UTC, thorrellt commented
The TwoColumns component was very dependent on custom classes. There are a lot of variations of it's components based on these classes.  In order to keep the files kinda clean and readable I put all that logic in a separate file, and return the css via a function. like: 
![image](https://user-images.githubusercontent.com/64343445/230397255-b1d980fc-fe04-4045-a2bf-49c4badf4a15.png)

If anyone has the time, can they check out my thought process and let me know if it makes sense? and if they can think of a better solution if this isnt a good design choice? thanks

2023-04-13 02:11 UTC, mariana-caldas commented
> The TwoColumns component was very dependent on custom classes. There are a lot of variations of it's components based on these classes. In order to keep the files kinda clean and readable I put all that logic in a separate file, and return the css via a function. like: ![image](https://user-images.githubusercontent.com/64343445/230397255-b1d980fc-fe04-4045-a2bf-49c4badf4a15.png)
> 
> If anyone has the time, can they check out my thought process and let me know if it makes sense? and if they can think of a better solution if this isnt a good design choice? thanks

Hi @thorrellt !

I totally see your point about the `addContentsCss.js` file and the number of props we have for the `TwoColumn`. What if we try to simplify it by having 3 TwoColumn components? The first would be the regular `TwoColumn.js` with no custom classes. The second and third would extend TwoColumn to become TwoColumnHomepage and TwoColumnAboutUs with all their respective props.

I suggest that because the approach with addContentsCss seems less readable to me than the regular Sass approach we were using before for that confusing component, so maybe that's a repetition that would make us understand better the codebase. How do you see that?

2023-04-13 13:26 UTC, thorrellt commented
> Hi @thorrellt !
> 
> I totally see your point about the `addContentsCss.js` file and the number of props we have for the `TwoColumn`. What if we try to simplify it by having 3 TwoColumn components? The first would be the regular `TwoColumn.js` with no custom classes. The second and third would extend TwoColumn to become TwoColumnHomepage and TwoColumnAboutUs with all their respective props.
> 
> I suggest that because the approach with addContentsCss seems less readable to me than the regular Sass approach we were using before for that confusing component, so maybe that's a repetition that would make us understand better the codebase. How do you see that?

I see where you're coming from. I'm not sure extension is possible, as it seems to be tricky with components, especially with nested components because the extension doesn't account for them. However, doing two different implementations could/should work. 

I will play with it and do some research over the next few days. Either way, there will be multiple TwoColumn components to improve readability.

2023-04-22 01:22 UTC, mariana-caldas requested changes
You're are doing a great job so far, @thorrellt !

I'd like to ask for some changes about the first components I could review and I ask you to reflect on them for the other components' conversion before I go forward, please.
The main reason we're converting those components into `styled-components` is to improve the readability so I'd rather see more extended components than `props` or custom classes whenever possible, please.

2023-04-22 01:22 UTC, mariana-caldas commented on components/buttons/SubmitButton/styles.js
> +      props.$buttonType === 'newsletter__button'
To make the code more readable, I'd rather remove the `buttonType` prop and extend the `SubmitButton` to the other ones if possible.

2023-04-22 01:22 UTC, mariana-caldas commented on components/containers/Card/styles.js
> +  ${props => (props.$cardType === 'our-goals' ? AboutUs : '')}
I'd rather see the Card component extended to other "children" than props.

2023-04-22 01:28 UTC, cherylli reviewed
Looks good. Thanks for doing this, it's a very big task!

Not sure if it's just me, is anyone else getting this on every page load?
![image](https://user-images.githubusercontent.com/6191116/233754258-e90cf803-528e-42d4-8d36-7c1487ee3548.png)

2023-04-22 02:03 UTC, mariana-caldas commented
> Looks good. Thanks for doing this, it's a very big task!
> 
> Not sure if it's just me, is anyone else getting this on every page load? ![image](https://user-images.githubusercontent.com/6191116/233754258-e90cf803-528e-42d4-8d36-7c1487ee3548.png)

Hey, @cherylli ! Thanks for your feedback. 
I don't see those errors when I run this branch locally from a Windows PC on Chrome (attached). However, I see some warnings referent to our `pwa` and `styled-components` that may require we update our Next.js version to the latest and, then, change a little bit our `next,config.js` file later in another task. Please let us know if you need some supporting to find out why do you see those errors in your end, I'd recommend to remove your `node_modules`  and install the dependencies again just to make sure any weird package is corrupting your local environment.

![image](https://user-images.githubusercontent.com/20016897/233755899-0e27bafb-2c4a-4e94-a214-28fed7abaad3.png)

2023-04-22 06:04 UTC, cherylli commented
> > Looks good. Thanks for doing this, it's a very big task!
> > Not sure if it's just me, is anyone else getting this on every page load? ![image](https://user-images.githubusercontent.com/6191116/233754258-e90cf803-528e-42d4-8d36-7c1487ee3548.png)
> 
> Hey, @cherylli ! Thanks for your feedback. I don't see those errors when I run this branch locally from a Windows PC on Chrome (attached). However, I see some warnings referent to our `pwa` and `styled-components` that may require we update our Next.js version to the latest and, then, change a little bit our `next.config.js` file later in another task. Please let us know if you need support to find out why you see those errors on your end, I'd recommend removing your `node_modules` and installing the dependencies again to make sure any weird package is corrupting your local environment.
> 
> ![image](https://user-images.githubusercontent.com/20016897/233755899-0e27bafb-2c4a-4e94-a214-28fed7abaad3.png)

I've deleted .next and node_modules and still seeing this, but not in the terminal. I saw it in the browser inspector. It seems to be only a chrome issue for me. I might look into it when I have more time.

2023-05-01 16:06 UTC, thorrellt commented
> You're are doing a great job so far, @thorrellt !
> 
> I'd like to ask for some changes about the first components I could review and I ask you to reflect on them for the other components' conversion before I go forward, please. The main reason we're converting those components into `styled-components` is to improve the readability so I'd rather see more extended components than `props` or custom classes whenever possible, please.

So can you look at how I did Two Columns and let me know if that is acceptable?  Two columns has 11 variations that are made up of probably 20+ extended components. I packaged these components into objects then assign them in TwoColumns.js based on a a singled  prop ($contentType) that is received when TwoColumns is called. It is passed and referenced only one time. This way when "about-us" references the <S.Title> component, S.Title is a key that actually references S.AboutUsTitle. 

If I extend TwoColums then we will have 11 versions of it b/c I cannot think of how else to change the internal components that make up the TwoColumn container. If ever any changes need to happen to it, it will have to be repeated 11 times.

Do you think this design pattern will work? It 
- eliminated the use of props to inject CSS like u referenced before.
- removed all props passing from inside the parent container to clean up the code.
- All the logic for which set of extended components to use is done in these lines of code
![image](https://user-images.githubusercontent.com/64343445/235483825-c4e9ecae-1ca6-472f-856b-3ff8765a4266.png)

Thoughts?

2023-05-01 16:21 UTC, thorrellt commented on CHANGELOG.md
> +- error where html loaded before styles by updating \_document.js
will do

2023-05-01 17:06 UTC, mariana-caldas commented
> > You're are doing a great job so far, @thorrellt !
> > I'd like to ask for some changes about the first components I could review and I ask you to reflect on them for the other components' conversion before I go forward, please. The main reason we're converting those components into `styled-components` is to improve the readability so I'd rather see more extended components than `props` or custom classes whenever possible, please.
> 
> So can you look at how I did Two Columns and let me know if that is acceptable? Two columns has 11 variations that are made up of probably 20+ extended components. I packaged these components into objects then assign them in TwoColumns.js based on a a singled prop ($contentType) that is received when TwoColumns is called. It is passed and referenced only one time. This way when "about-us" references the <S.Title> component, S.Title is a key that actually references S.AboutUsTitle.
> 
> If I extend TwoColums then we will have 11 versions of it b/c I cannot think of how else to change the internal components that make up the TwoColumn container. If ever any changes need to happen to it, it will have to be repeated 11 times.
> 
> Do you think this design pattern will work? It
> 
> * eliminated the use of props to inject CSS like u referenced before.
> * removed all props passing from inside the parent container to clean up the code.
> * All the logic for which set of extended components to use is done in these lines of code
>   ![image](https://user-images.githubusercontent.com/64343445/235483825-c4e9ecae-1ca6-472f-856b-3ff8765a4266.png)
> 
> Thoughts?

Yeah, I'd say to focus on revisiting the other components to check if we can extend them instead of using customClasses and leaving the TwoColumns as the least one while we think if there is another way to simplify it or if that's the best approach, @thorrellt . Please let me know if that makes sense!

2023-05-01 17:30 UTC, thorrellt commented
> > > You're are doing a great job so far, @thorrellt !
> > > I'd like to ask for some changes about the first components I could review and I ask you to reflect on them for the other components' conversion before I go forward, please. The main reason we're converting those components into `styled-components` is to improve the readability so I'd rather see more extended components than `props` or custom classes whenever possible, please.
> > 
> > 
> > So can you look at how I did Two Columns and let me know if that is acceptable? Two columns has 11 variations that are made up of probably 20+ extended components. I packaged these components into objects then assign them in TwoColumns.js based on a a singled prop ($contentType) that is received when TwoColumns is called. It is passed and referenced only one time. This way when "about-us" references the <S.Title> component, S.Title is a key that actually references S.AboutUsTitle.
> > If I extend TwoColums then we will have 11 versions of it b/c I cannot think of how else to change the internal components that make up the TwoColumn container. If ever any changes need to happen to it, it will have to be repeated 11 times.
> > Do you think this design pattern will work? It
> > 
> > * eliminated the use of props to inject CSS like u referenced before.
> > * removed all props passing from inside the parent container to clean up the code.
> > * All the logic for which set of extended components to use is done in these lines of code
> >   ![image](https://user-images.githubusercontent.com/64343445/235483825-c4e9ecae-1ca6-472f-856b-3ff8765a4266.png)
> > 
> > Thoughts?
> 
> Yeah, I'd say to focus on revisiting the other components to check if we can extend them instead of using customClasses and leaving the TwoColumns as the least one while we think if there is another way to simplify it or if that's the best approach, @thorrellt . Please let me know if that makes sense!

I understand @mariana-caldas. Much thanks for the feedback, and sorry for my slow response/follow-up.

2023-05-05 17:30 UTC, thorrellt commented on components/containers/Container/Container.js
> +  className,
I removed the customClass, but the classname has to stay. It's part of extending Styled Components (i think.) I specifically added this as a fix a while back, so I forgot where is the docs I read this. But if we remove customer class, certain styles wont pass correctly.

2023-05-08 02:57 UTC, mariana-caldas requested changes
We're almost there, @thorrellt ! Such a great job! 🥷

2023-05-08 02:57 UTC, mariana-caldas commented on components/layout/Footer/styles.js
> +  max-width: 12.5rem;
Please remove the properties `display`, `max-width`, and `margin` here. They are preventing centering the logo properly on mobile.

2023-05-08 02:57 UTC, mariana-caldas commented on components/mailchimp/NewsletterForm/styles.js
> +// .newsletterFormInfo {
Please remove all the comments.

2023-05-08 02:57 UTC, mariana-caldas commented on components/containers/Card/styles.js
> +// export default {
Please remove the comments.

2023-05-08 02:57 UTC, mariana-caldas commented on components/containers/CardColumns/CardColumnsInterface.js
> +export function CardsColumnsInterface({ cards, customClass, cardComponent }) {
What a great idea to create an interface handled through a property!

2023-05-11 03:51 UTC, cherylli reviewed
Thanks for the changes. I didn't check all of the files but there are a few files with unused imports which should be removed. For example, in Container/rows/index.js and TwoColumn/index.js

the grey part are unused variables and imports
![image](https://github.com/Web-Dev-Path/web-dev-path/assets/6191116/ecdeecb0-ea25-4ef5-8a4d-24694114a14e)
![image](https://github.com/Web-Dev-Path/web-dev-path/assets/6191116/ef368f0a-9aed-478b-9986-bdb5d0b5dfe6)

2023-05-12 01:36 UTC, cherylli reviewed
Thanks for the new commit, I still see some unused imports and variables. Were they just missed or left there on purpose?

Otherwise everything looks good.

2023-05-12 11:27 UTC, cherylli commented
> 

My IDE (webstorm) shows unused imports/variables in grey, vscode has similar thing, I guess a lot of editors and IDE will have similar features

For example here customClass is not in used, you have removed some in this file but not customClass so I was just wonder if there's any other reasons for this

![image](https://github.com/Web-Dev-Path/web-dev-path/assets/6191116/51bdff48-1e9a-4f36-9aa9-83ec50ae292e)

TwoColumns still has some unused imports 
![image](https://github.com/Web-Dev-Path/web-dev-path/assets/6191116/cf41dac7-2165-41a5-b7af-af845c80beb4)


But just go into each file and have a quick look.

webstorm does have an "Optimize Imports" function to remove all unused imports

This is also in Webstorm, you can scan for problems in the whole project.
![image](https://github.com/Web-Dev-Path/web-dev-path/assets/6191116/0d9d1504-a57f-4aec-83dd-4764c78f7e21)

2023-05-16 22:28 UTC, mariana-caldas commented on components/containers/Card/CardInterface.js
> +export function CardInterface({
It makes total sense to see this component as an interface!

2023-05-16 23:19 UTC, mariana-caldas approved these changes
Such a great job, @thorrellt ! 🥇

2023-05-17 03:04 UTC, cherylli approved these changes
looks good!

2023-05-20 12:35 UTC, merged