Integrate Google Analytics 4
Web-Dev-Path/web-dev-path pull request #178
Opened 2023-07-09 18:38 UTC by LuSilvaDeveloper

|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**177**](https://github.com/Web-Dev-Path/web-dev-path/issues/177) |

#### Have you updated the CHANGELOG.md file? If not, please do it.

Yes.

#### What is this change?

Integrated Google Analytics 4 (GA4) using the library next-ga.

#### Were there any complications while making this change?

No.

#### How did you verify this change?

I tested it locally using many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).

#### When should this be merged?

After review

2023-07-09 20:58 UTC, mariana-caldas commented
Hey @LuSilvaDeveloper !

Great job on submitting your first PR 🎉 

Can you please do the following steps?
1.  delete the `.yarn` folder with your local yarn configurations, 
2. add the following to our `.gitignore` since we don't want to version control your local cache.

```
.yarn/*
!.yarn/releases
!.yarn/plugins
!.yarn/sdks
```
3. commit the change

https://stackoverflow.com/questions/69885538/should-i-push-the-yarn-cache-folder-to-github-yarn2

Please let me know if you have any questions!

2023-07-09 21:51 UTC, LuSilvaDeveloper commented
Hey @mariana-caldas .
Thank you!
I've already fixed it.

2023-07-10 14:09 UTC, cherylli reviewed
Hi, thanks for the PR, just left a few comments, I'm still waiting for the key to test out the app locally

2023-07-10 14:09 UTC, cherylli commented on package.json
> +    "dotenv": "^16.3.1",
I believe dotenv is not required for next.js

2023-07-10 14:09 UTC, cherylli commented on pages/_app.js
> +require('dotenv').config();
as above, dotenv is not requried for next.js

2023-07-11 02:55 UTC, mariana-caldas requested changes
Other than the comments Cheryl mentions about the "dotenv" unnecessary library, I think we're good to!

2023-07-11 03:44 UTC, LuSilvaDeveloper commented on pages/_app.js
> +require('dotenv').config();
alright. Thank you! I've already uninstalled the dotenv library.

2023-07-11 22:08 UTC, sergiobtos approved these changes
Looks good. All the possible changes were already made by the team.

2023-07-12 02:04 UTC, cherylli approved these changes
Looks good!

2023-07-12 04:41 UTC, mariana-caldas approved these changes
Great job, @LuSilvaDeveloper !

2023-07-12 16:27 UTC, merged