Feature/add theming
Web-Dev-Path/web-dev-path pull request #210
Opened 2024-01-16 14:50 UTC by LuSilvaDeveloper

|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**165**](https://github.com/MarianaSouza/web-dev-path/issues/165) |

#### Have you updated the CHANGELOG.md file? If not, please do it.

Yes.

#### What is this change?

Adding theming to the project to have centralized all SASS variables previously spread across _mixins.js and _variables.js into themeConfig.js for better organization. 

Some questions:

- We have some components that were using both SASS and normal CSS, for example, inside `styles.js` from `Hero` we have the `HeaderContent` which was previously using SASS for `color` and normal CSS for `padding-top`. The best approach should be keeping the of `padding-top` inside the `styles.js` file, and `color` we keep it inside `themeConfig.js`?

<img width="548" alt="Screenshot 2024-01-16 at 6 40 12 AM" src="https://github.com/Web-Dev-Path/web-dev-path/assets/107877216/15dcb478-96cc-4346-8903-15c5f855f338">

- Should we pass all attributes inside `globals.scss` to `themeConfig.js` on `GlobalStyles` or should we keep only the attributes that were using SASS inside `themeConfig.js`, similarly to the previous question?

<img width="527" alt="Screenshot 2024-01-16 at 6 50 00 AM" src="https://github.com/Web-Dev-Path/web-dev-path/assets/107877216/5fdc712a-dfe8-48eb-a4cb-cb9fc9601477">

<img width="506" alt="Screenshot 2024-01-16 at 6 50 20 AM" src="https://github.com/Web-Dev-Path/web-dev-path/assets/107877216/1221042f-ab57-410f-b391-405b4593927a">

The next step would be passing these attributes to all components, making sure everything is working.

#### Were there any complications while making this change?

Mostly misunderstanding on my part regarding the issue

#### How to replicate the issue?

Run on different browsers.

#### If necessary, please describe how to test the new feature or fix.

NA

#### When should this be merged?

2024-01-17 01:33 UTC, cherylli reviewed
Thanks. It works locally without any errors but I just have a few questions. Please see inline comments 

Also I see a lot of commented code, are they all needed?

2024-01-17 01:33 UTC, cherylli commented on themeConfig.js
> +  breakpoints: {
wouldn't the light and dark theme have the same breakpoints?

2024-01-17 01:33 UTC, cherylli commented on styles/globals.scss
> +  // font-family: $copy-font, sans-serif;
can these commented code be removed? or are we keeping them for something?

2024-01-17 01:33 UTC, cherylli commented on components/layout/Footer/styles.js
> +    display: ${({ theme }) => theme.display};
does changing theme change the layout too? I have an impression that it would just be the colour

2024-01-17 01:33 UTC, cherylli commented on components/layout/Hero/styles.js
> +  color: ${({ theme }) => theme.colors.white};
would this always be white regardless of the theme? or is "white" a different shade of white depending on the theme?

2024-02-20 13:26 UTC, LuSilvaDeveloper commented on styles/globals.scss
> +  // font-family: $copy-font, sans-serif;
Sure. I'm removing it.

2024-02-20 13:29 UTC, LuSilvaDev commented on components/layout/Hero/styles.js
> +  color: ${({ theme }) => theme.colors.white};
It would be always white. But the point here was removing the SASS and put this color inside themeConfig

2024-02-20 13:35 UTC, LuSilvaDeveloper commented on themeConfig.js
> +  breakpoints: {
I think so. But for the first moment, it's supposed to get the variables using SASS and put it on the themeConfig, and I'm just leaving the darkTheme ready for further implementation

2024-02-20 13:40 UTC, LuSilvaDeveloper commented on components/layout/Hero/styles.js
> +  color: ${({ theme }) => theme.colors.white};
Yes. But The point is changing from SASS to have this variable inside themeConfig.

2024-02-20 23:42 UTC, cherylli commented on components/layout/Hero/styles.js
> +  color: ${({ theme }) => theme.colors.white};
I think it's fine for now. This allows us to have slightly different shade of white in different themes. Also, since we don't really have another theme yet we don't really know what it would be in another theme, it could be like a secondary color

2024-03-10 10:32 UTC, cherylli reviewed
everything works fine locally, I just have a few questions

2024-03-10 10:32 UTC, cherylli commented on components/layout/Footer/styles.js
> +  transition: all 0.3s ease; // is it the same as the transition mixin?
I don't really know mixin but looks like you'll have to use `@include`
https://stackoverflow.com/questions/62999437/how-to-create-a-transform-mixin-in-scss-that-uses-several-arguments

someone correct me if I'm wrong

2024-03-10 10:32 UTC, cherylli commented on themeConfig.js
> +  a: { // change the name
whats "change the name"?

2024-03-11 21:53 UTC, LuSilvaDeveloper commented on themeConfig.js
I think it depends on the design that we want for the app. It should work fine since it makes everything global on the application. Do you think is it better to put it in the styles folder?

2024-03-11 21:54 UTC, LuSilvaDeveloper commented on themeConfig.js
> +  a: { // change the name
I just forgot to delete this comment

2024-03-12 03:14 UTC, cherylli commented on themeConfig.js
I think we should put in the styles folder as it's style related. I don't think you need to put it in the root for it to be globally accessible

2024-03-12 05:05 UTC, mariana-caldas requested changes
We are getting close, @LuSilvaDeveloper ! Great job!

Besides our comments, it's important that at the end, we have no `.scss` files inside our `styles` folder since any global style should be implemented within the `themeConfig.js` file.

I answered the questions you added to the PR body on Slack. Can you please remove them from the PR body? Ideally, the PR description will give us information in the future so, I'd say ask things on Slack or use the comments.

Can you please request our review again after you implement the changes? Thanks, so much, Lucas!

2024-03-12 05:13 UTC, mariana-caldas commented on components/containers/TwoColumn/styles.js
> +    }
Please fix the typo "height" here and test it out with different breakpoints.

2024-03-12 05:18 UTC, mariana-caldas commented on components/layout/Footer/styles.js
> +      padding-left: 28px;
Let's keep using only rem not px, please.

2024-03-12 05:27 UTC, mariana-caldas commented on components/layout/Footer/styles.js
> +  transition: all 0.3s ease; // is it the same as the transition mixin?
I think since we're using styled-components, the implementation is a little bit different, @cherylli.

We should have the variables and mixins inside themeConfig as well, @LuSilvaDeveloper, so we can get rid of any scss file. Then, we indeed use the transition from the mixin function we get from the themeConfig file.

2024-03-25 18:16 UTC, LuSilvaDeveloper commented on themeConfig.js
> +export const darkTheme = {};
It makes a lot of sense! thank you!

2024-03-25 18:17 UTC, LuSilvaDeveloper commented on components/containers/TwoColumn/styles.js
> +    }
Done!

2024-03-25 19:01 UTC, LuSilvaDeveloper commented
I think I've done the changes as required. Please let me know if it's correct. Also, once is reviewed, I will delete the globals.scss file.

2024-05-22 02:09 UTC, cherylli commented
thanks! Everything looks good to me!

2024-05-22 02:10 UTC, cherylli approved these changes
thanks! Everything looks good to me!

2024-05-22 04:31 UTC, mariana-caldas approved these changes
Such a great job, @LuSilvaDeveloper ! 🚀 
I will leave this PR approved, however, before merging it. Can you please take a look at the comment on SubmitButton/index? Thanks so much!

2024-05-22 04:31 UTC, mariana-caldas commented on components/buttons/SubmitButton/index.js
> +export function SubmitButton({ label, disabled }) { {}
Can you help us to confirm why we need this {} on line 3, @LuSilvaDeveloper ?

2024-05-22 04:52 UTC, LuSilvaDeveloper commented on components/buttons/SubmitButton/index.js
> +export function SubmitButton({ label, disabled }) { {}
Actually, we don't need it. It's unnecessary.

2024-05-22 16:51 UTC, merged