updated TwoColumn.js
Web-Dev-Path/web-dev-path pull request #82
Opened 2022-03-01 04:45 UTC by vmcodes

|                                    Web Dev Path                                    |
| :--------------------------------------------------------------------------------: |
| [**81**](https://github.com/Web-Dev-Path/web-dev-path/issues/81) |

#### Have you updated the CHANGELOG.md file? If not, please do it.
Yes

#### What is this change?
Updated TwoColumn.js

#### Were there any complications while making this change?
Had to update ButtonLink.js to accept style props as well.

#### How did you verify this change?

#### When should this be merged?

2022-03-01 23:50 UTC, manecipoglu reviewed
Very nice PR Vincent. Thank you.

2022-03-01 23:50 UTC, manecipoglu commented on pages/index.js
> +        btnColor="#292929"
I believe we have this color defined in our variables partial but because we are passing them to the component as props, I don't think we can pull them easily like we do with the scss files. Is there a way to do that? 

I realize the issue is asking for changeable props for background color and text color but maybe a solution can be found by passing a className as prop instead of passing the styles. This way we can apply the "separation of concerns" principles. This has the downside of compiling more css than necessary whenever we want to use TwoColumns component with different styling. What do you think @mariana-caldas ?

2022-03-01 23:50 UTC, manecipoglu commented on components/TwoColumn.js
> +        {image && (
Good use of conditional rendering here.

2022-03-02 00:26 UTC, mariana-caldas requested changes
This is such a great PR, @vmcodes ! I only see small adjustments. Please let m know if you need any help to implement them and after you commit those changes, could you please [request our review again](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) ? Thank you! 🚀

2022-03-02 00:26 UTC, mariana-caldas commented on components/TwoColumn.js
> +  const styleProps = {
It's an elegant solution to add all those style props in a single object, @vmcodes ! Well done!

2022-03-02 00:26 UTC, mariana-caldas commented on components/TwoColumn.js
> +            link="/about-us"
Could you please create a prop to pass the `<ButtonLink />` string link dynamically when calling the component as well, @vmcodes ? It's possible that we're going to use the `TwoColumns.js` with a different link in other situations. Thanks!

2022-03-02 00:26 UTC, mariana-caldas commented on pages/index.js
> +        btnColor="#292929"
This is one of the unique cases the use of inline styling makes sense to me, @manecipoglu. Because we're just changing colors and the idea is to reuse this component as much as we need, I think it is fine to keep specific props as is. However, great point on highlighting the use of variables here, Muammer! I agree with you.

Could you please follow this [step 3 tutorial ](https://spacejelly.dev/posts/how-to-export-sass-variables-to-javascript-with-next-js/)to export the color variables from our [variables file](https://github.com/Web-Dev-Path/web-dev-path/blob/master/styles/_variables.scss) and import them here, @vmcodes ? Please let m know if you need any assistance with that! Thanks :)

2022-03-02 05:22 UTC, manecipoglu commented on pages/index.js
> +        btnColor="#292929"
> Could you please follow this [step 3 tutorial ](https://spacejelly.dev/posts/how-to-export-sass-variables-to-javascript-with-next-js/)to export the color variables from our [variables file](https://github.com/Web-Dev-Path/web-dev-path/blob/master/styles/_variables.scss) and import them here

This is exactly what I wanted to do instead. I wasn't aware of the :exports syntax. Good to know. Thanks for the link!

2022-03-03 01:35 UTC, mariana-caldas requested changes
We only need to export the color variables from the right file (https://github.com/Web-Dev-Path/web-dev-path/blob/master/styles/_variables.scss) to finish this PR, @vmcodes!
We're getting close! 🚀

2022-03-03 01:35 UTC, mariana-caldas commented on styles/TwoColumn.module.scss
> +
The idea of exporting the colors is correct, @vmcodes , however, we should do that from our `variables.scss` file  instead -> https://github.com/Web-Dev-Path/web-dev-path/blob/master/styles/_variables.scss

2022-03-03 02:18 UTC, vmcodes commented on styles/TwoColumn.module.scss
> +
I received the following error when trying to do that, which is why I moved them to TwoColumn.module.scss.

./styles/_variables.scss
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: pages\index.js

2022-03-03 02:23 UTC, vmcodes commented on styles/TwoColumn.module.scss
> +
I should have listed that under complications.

2022-03-03 02:23 UTC, manecipoglu commented on styles/TwoColumn.module.scss
> +
I am not sure but can you try without the underscore "_" ? Like this: ./styles/variables.scss

2022-03-03 02:41 UTC, mariana-caldas commented on styles/TwoColumn.module.scss
> +
Oh, I see. That makes sense! Thanks for checking that, @vmcodes !

2022-03-03 02:43 UTC, mariana-caldas approved these changes
LGTM, @vmcodes ! Great job!
It's all yours to [merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request) :whenever you have a moment!

2022-03-03 02:50 UTC, merged